import { ClerkProvider } from "@clerk/nextjs"
import '../globals.css'
import type { Metadata } from 'next'
import {dark} from '@clerk/themes';
import { Inter } from 'next/font/google'
import Topbar from "@/components/shared/Topbar"
import LeftSidebar from "@/components/shared/Leftsidebar"
import RightSidebar from "@/components/shared/Rightsidebar"
import Bottombar from "@/components/shared/Bottombar"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tweethread',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <Topbar/>
            <main className="flex flex-row">
              <LeftSidebar/>
                <section className="main-container bg-dark-1 max-md:pb-32 sm:px-10">
                  <div className="w-full max-w-4xl">
                    {children}
                  </div>
                </section>
                {/* @ts-ignore */}
              <RightSidebar/>
            </main>
          <Bottombar/>
        </body>
      </html>
    </ClerkProvider>
  )
}